/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.ventana;

import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.io.File;
import javax.imageio.ImageIO;

/**
 *
 * @author Usuario
 */
public class VentanaCarga extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCarga
     */
    public VentanaCarga(String rutaIcono) {
        initComponents();
        try {
            setIconImage(ImageIO.read(new File(rutaIcono)));
        } catch (Exception e) {
            e.printStackTrace();
        }
        setLocationRelativeTo(null);

        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 15, 15);

        AWTUtilities.setWindowShape(this, forma);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JLabel();
        barraProgreso = new barraprogreso.BarraProgreso();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/KnightFightFondo.png"))); // NOI18N
        fondo.setFocusable(false);
        getContentPane().add(fondo, java.awt.BorderLayout.CENTER);

        barraProgreso.setBackground(new java.awt.Color(0, 0, 0));
        barraProgreso.setForeground(new java.awt.Color(102, 0, 51));
        barraProgreso.setBorderPainted(false);
        barraProgreso.setStringPainted(true);
        getContentPane().add(barraProgreso, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private barraprogreso.BarraProgreso barraProgreso;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables

    public barraprogreso.BarraProgreso getBarraProgreso() {
        return barraProgreso;
    }
}
