/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panel;

import java.awt.event.ActionListener;
import javax.swing.JToggleButton;

/**
 *
 * @author Samuel Reyes
 *
 */
public class PanelEstado extends javax.swing.JPanel {

    /**
     * Creates new form PanelEstado
     */
    public PanelEstado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoInventario = new javax.swing.ButtonGroup();
        grupoEquipado = new javax.swing.ButtonGroup();
        menuInventario = new javax.swing.JPopupMenu();
        equipar = new javax.swing.JMenuItem();
        potenciar = new javax.swing.JMenuItem();
        vender = new javax.swing.JMenuItem();
        menuEquipado = new javax.swing.JPopupMenu();
        desequipar = new javax.swing.JMenuItem();
        potenciarE = new javax.swing.JMenuItem();
        pSuperior = new javax.swing.JPanel();
        psIzquierda = new javax.swing.JPanel();
        pTituloAtr = new javax.swing.JPanel();
        etTituloAtr = new javax.swing.JLabel();
        panelFuerza = new javax.swing.JPanel();
        pbFuerza = new javax.swing.JProgressBar();
        btnFuerza = new javax.swing.JButton();
        panelArmadura = new javax.swing.JPanel();
        pbArmadura = new javax.swing.JProgressBar();
        btnArmadura = new javax.swing.JButton();
        panelDestreza = new javax.swing.JPanel();
        pbDestreza = new javax.swing.JProgressBar();
        btnDestreza = new javax.swing.JButton();
        panelConstitucion = new javax.swing.JPanel();
        pbConstitucion = new javax.swing.JProgressBar();
        btnConstitucion = new javax.swing.JButton();
        panelAtrSinUsar = new javax.swing.JPanel();
        etAtrSinUsar = new javax.swing.JLabel();
        atributosSinUsar = new javax.swing.JLabel();
        psDerecha = new javax.swing.JPanel();
        pTituloEstadisticas = new javax.swing.JPanel();
        etTituloEstadisticas = new javax.swing.JLabel();
        pEstadisticas = new javax.swing.JPanel();
        etOroAcumulado = new javax.swing.JLabel();
        oroTotal = new javax.swing.JLabel();
        etCombates = new javax.swing.JLabel();
        combatesTotal = new javax.swing.JLabel();
        etVictorias = new javax.swing.JLabel();
        victoriasTotal = new javax.swing.JLabel();
        etEmpates = new javax.swing.JLabel();
        empatesTotal = new javax.swing.JLabel();
        etDerrotas = new javax.swing.JLabel();
        derrotasTotal = new javax.swing.JLabel();
        etAtaqueOcasionado = new javax.swing.JLabel();
        ataqueOcasionado = new javax.swing.JLabel();
        etAtaqueRecibido = new javax.swing.JLabel();
        ataqueRecibido = new javax.swing.JLabel();
        etMisiones = new javax.swing.JLabel();
        misionesTotal = new javax.swing.JLabel();
        pInferior = new javax.swing.JPanel();
        sTituloInventario = new javax.swing.JSplitPane();
        etTituloEquipado = new javax.swing.JLabel();
        etTituloInventario = new javax.swing.JLabel();
        separadorInventario = new javax.swing.JSplitPane();
        pEquipado = new javax.swing.JPanel();
        cinta = new javax.swing.JToggleButton();
        casco = new javax.swing.JToggleButton();
        collar = new javax.swing.JToggleButton();
        pendienteIzq = new javax.swing.JToggleButton();
        coraza = new javax.swing.JToggleButton();
        pendienteDer = new javax.swing.JToggleButton();
        escudo = new javax.swing.JToggleButton();
        pantalon = new javax.swing.JToggleButton();
        arma = new javax.swing.JToggleButton();
        anilloIzq = new javax.swing.JToggleButton();
        botas = new javax.swing.JToggleButton();
        anilloDer = new javax.swing.JToggleButton();
        pInventario = new javax.swing.JPanel();
        inventario1 = new javax.swing.JToggleButton();
        inventario2 = new javax.swing.JToggleButton();
        inventario3 = new javax.swing.JToggleButton();
        inventario4 = new javax.swing.JToggleButton();
        inventario5 = new javax.swing.JToggleButton();
        inventario6 = new javax.swing.JToggleButton();
        inventario7 = new javax.swing.JToggleButton();
        inventario8 = new javax.swing.JToggleButton();
        inventario9 = new javax.swing.JToggleButton();
        inventario10 = new javax.swing.JToggleButton();
        inventario11 = new javax.swing.JToggleButton();
        inventario12 = new javax.swing.JToggleButton();
        inventario13 = new javax.swing.JToggleButton();
        inventario14 = new javax.swing.JToggleButton();
        inventario15 = new javax.swing.JToggleButton();
        inventario16 = new javax.swing.JToggleButton();
        inventario17 = new javax.swing.JToggleButton();
        inventario18 = new javax.swing.JToggleButton();
        inventario19 = new javax.swing.JToggleButton();
        inventario20 = new javax.swing.JToggleButton();

        equipar.setText("Equipar");
        menuInventario.add(equipar);

        potenciar.setText("Potenciar");
        menuInventario.add(potenciar);

        vender.setText("Vender");
        menuInventario.add(vender);

        desequipar.setText("Desequipar");
        menuEquipado.add(desequipar);

        potenciarE.setText("Potenciar");
        menuEquipado.add(potenciarE);

        setMaximumSize(new java.awt.Dimension(650, 550));
        setMinimumSize(new java.awt.Dimension(650, 550));
        setPreferredSize(new java.awt.Dimension(700, 550));
        setLayout(new java.awt.GridLayout(2, 1));

        pSuperior.setLayout(new java.awt.GridLayout(1, 2));

        psIzquierda.setLayout(new java.awt.GridLayout(6, 1));

        etTituloAtr.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        etTituloAtr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etTituloAtr.setText("Atributos");

        javax.swing.GroupLayout pTituloAtrLayout = new javax.swing.GroupLayout(pTituloAtr);
        pTituloAtr.setLayout(pTituloAtrLayout);
        pTituloAtrLayout.setHorizontalGroup(
            pTituloAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTituloAtrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etTituloAtr, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        pTituloAtrLayout.setVerticalGroup(
            pTituloAtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTituloAtrLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(etTituloAtr, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        psIzquierda.add(pTituloAtr);

        pbFuerza.setMaximum(5);
        pbFuerza.setToolTipText("1 Fuerza = 2 Ataque Min y 2 Ataque Max");
        pbFuerza.setValue(5);
        pbFuerza.setPreferredSize(new java.awt.Dimension(250, 20));
        pbFuerza.setString("Fuerza 5");
        pbFuerza.setStringPainted(true);
        panelFuerza.add(pbFuerza);

        btnFuerza.setText("+");
        btnFuerza.setToolTipText("Gastar punto en subir Fuerza");
        btnFuerza.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnFuerza.setPreferredSize(new java.awt.Dimension(40, 37));
        panelFuerza.add(btnFuerza);

        psIzquierda.add(panelFuerza);

        pbArmadura.setMaximum(5);
        pbArmadura.setToolTipText("1 Armadura = 2 Defensa Min y 2 Defensa Max");
        pbArmadura.setValue(5);
        pbArmadura.setPreferredSize(new java.awt.Dimension(250, 20));
        pbArmadura.setString("Armadura 5");
        pbArmadura.setStringPainted(true);
        panelArmadura.add(pbArmadura);

        btnArmadura.setText("+");
        btnArmadura.setToolTipText("Gastar punto en subir Armadura");
        btnArmadura.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnArmadura.setPreferredSize(new java.awt.Dimension(40, 37));
        panelArmadura.add(btnArmadura);

        psIzquierda.add(panelArmadura);

        pbDestreza.setMaximum(5);
        pbDestreza.setToolTipText("1 Destreza = 1 Ataque Max y 1 Defensa Max");
        pbDestreza.setValue(5);
        pbDestreza.setPreferredSize(new java.awt.Dimension(250, 20));
        pbDestreza.setString("Destreza 5");
        pbDestreza.setStringPainted(true);
        panelDestreza.add(pbDestreza);

        btnDestreza.setText("+");
        btnDestreza.setToolTipText("Gastar punto en subir Destreza");
        btnDestreza.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDestreza.setPreferredSize(new java.awt.Dimension(40, 37));
        panelDestreza.add(btnDestreza);

        psIzquierda.add(panelDestreza);

        pbConstitucion.setMaximum(5);
        pbConstitucion.setToolTipText("1 Constitucion = 20 Vida Max");
        pbConstitucion.setValue(5);
        pbConstitucion.setPreferredSize(new java.awt.Dimension(250, 20));
        pbConstitucion.setString("Constitucion 5");
        pbConstitucion.setStringPainted(true);
        panelConstitucion.add(pbConstitucion);

        btnConstitucion.setText("+");
        btnConstitucion.setToolTipText("Gastar punto en subir Constitucion y curar al personaje");
        btnConstitucion.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnConstitucion.setPreferredSize(new java.awt.Dimension(40, 37));
        panelConstitucion.add(btnConstitucion);

        psIzquierda.add(panelConstitucion);

        etAtrSinUsar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etAtrSinUsar.setText("Puntos pendientes de asignar:");
        etAtrSinUsar.setToolTipText("Se obtiene 3 puntos por nivel de jugador");
        etAtrSinUsar.setPreferredSize(new java.awt.Dimension(200, 25));
        panelAtrSinUsar.add(etAtrSinUsar);

        atributosSinUsar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        atributosSinUsar.setText("0");
        atributosSinUsar.setToolTipText("Consigue puntos subiendo de nivel");
        atributosSinUsar.setPreferredSize(new java.awt.Dimension(100, 25));
        panelAtrSinUsar.add(atributosSinUsar);

        psIzquierda.add(panelAtrSinUsar);

        pSuperior.add(psIzquierda);

        psDerecha.setLayout(new java.awt.BorderLayout());

        pTituloEstadisticas.setPreferredSize(new java.awt.Dimension(326, 45));

        etTituloEstadisticas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        etTituloEstadisticas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etTituloEstadisticas.setText("Estadisticas");

        javax.swing.GroupLayout pTituloEstadisticasLayout = new javax.swing.GroupLayout(pTituloEstadisticas);
        pTituloEstadisticas.setLayout(pTituloEstadisticasLayout);
        pTituloEstadisticasLayout.setHorizontalGroup(
            pTituloEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTituloEstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etTituloEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        pTituloEstadisticasLayout.setVerticalGroup(
            pTituloEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTituloEstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etTituloEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        psDerecha.add(pTituloEstadisticas, java.awt.BorderLayout.NORTH);

        pEstadisticas.setLayout(new java.awt.GridLayout(8, 2));

        etOroAcumulado.setText("Total oro conseguido:");
        pEstadisticas.add(etOroAcumulado);

        oroTotal.setText("0");
        pEstadisticas.add(oroTotal);

        etCombates.setText("Total combates:");
        pEstadisticas.add(etCombates);

        combatesTotal.setText("0");
        pEstadisticas.add(combatesTotal);

        etVictorias.setText("Victorias obtenidas:");
        pEstadisticas.add(etVictorias);

        victoriasTotal.setText("0");
        pEstadisticas.add(victoriasTotal);

        etEmpates.setText("Empates conseguidos:");
        pEstadisticas.add(etEmpates);

        empatesTotal.setText("0");
        pEstadisticas.add(empatesTotal);

        etDerrotas.setText("Derrotas sufridas:");
        pEstadisticas.add(etDerrotas);

        derrotasTotal.setText("0");
        pEstadisticas.add(derrotasTotal);

        etAtaqueOcasionado.setText("Ataque total ocasionado:");
        pEstadisticas.add(etAtaqueOcasionado);

        ataqueOcasionado.setText("0");
        pEstadisticas.add(ataqueOcasionado);

        etAtaqueRecibido.setText("Ataque total recibido:");
        pEstadisticas.add(etAtaqueRecibido);

        ataqueRecibido.setText("0");
        pEstadisticas.add(ataqueRecibido);

        etMisiones.setText("Total misiones realizadas:");
        pEstadisticas.add(etMisiones);

        misionesTotal.setText("0");
        pEstadisticas.add(misionesTotal);

        psDerecha.add(pEstadisticas, java.awt.BorderLayout.CENTER);

        pSuperior.add(psDerecha);

        add(pSuperior);

        pInferior.setLayout(new java.awt.BorderLayout());

        sTituloInventario.setDividerLocation(250);
        sTituloInventario.setDividerSize(2);
        sTituloInventario.setEnabled(false);

        etTituloEquipado.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        etTituloEquipado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etTituloEquipado.setText("Equipado");
        etTituloEquipado.setPreferredSize(new java.awt.Dimension(199, 32));
        sTituloInventario.setLeftComponent(etTituloEquipado);

        etTituloInventario.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        etTituloInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etTituloInventario.setText("Inventario");
        sTituloInventario.setRightComponent(etTituloInventario);

        pInferior.add(sTituloInventario, java.awt.BorderLayout.NORTH);

        separadorInventario.setDividerLocation(250);
        separadorInventario.setDividerSize(2);
        separadorInventario.setEnabled(false);

        pEquipado.setLayout(new java.awt.GridLayout(4, 3));

        grupoEquipado.add(cinta);
        cinta.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        cinta.setBorderPainted(false);
        cinta.setEnabled(false);
        cinta.setFocusable(false);
        pEquipado.add(cinta);

        grupoEquipado.add(casco);
        casco.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        casco.setText("Casco");
        casco.setComponentPopupMenu(menuEquipado);
        casco.setMargin(new java.awt.Insets(0, 0, 0, 0));
        casco.setName("casco"); // NOI18N
        pEquipado.add(casco);

        grupoEquipado.add(collar);
        collar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        collar.setBorderPainted(false);
        collar.setEnabled(false);
        collar.setFocusable(false);
        pEquipado.add(collar);

        grupoEquipado.add(pendienteIzq);
        pendienteIzq.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        pendienteIzq.setBorderPainted(false);
        pendienteIzq.setEnabled(false);
        pendienteIzq.setFocusable(false);
        pEquipado.add(pendienteIzq);

        grupoEquipado.add(coraza);
        coraza.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        coraza.setText("Coraza");
        coraza.setComponentPopupMenu(menuEquipado);
        coraza.setMargin(new java.awt.Insets(0, 0, 0, 0));
        coraza.setName("coraza"); // NOI18N
        pEquipado.add(coraza);

        grupoEquipado.add(pendienteDer);
        pendienteDer.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        pendienteDer.setBorderPainted(false);
        pendienteDer.setEnabled(false);
        pendienteDer.setFocusable(false);
        pEquipado.add(pendienteDer);

        grupoEquipado.add(escudo);
        escudo.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        escudo.setText("Escudo");
        escudo.setComponentPopupMenu(menuEquipado);
        escudo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        escudo.setName("escudo"); // NOI18N
        pEquipado.add(escudo);

        grupoEquipado.add(pantalon);
        pantalon.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        pantalon.setText("Pantalon");
        pantalon.setComponentPopupMenu(menuEquipado);
        pantalon.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pantalon.setName("pantalon"); // NOI18N
        pEquipado.add(pantalon);

        grupoEquipado.add(arma);
        arma.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        arma.setText("Arma");
        arma.setComponentPopupMenu(menuEquipado);
        arma.setMargin(new java.awt.Insets(0, 0, 0, 0));
        arma.setName("arma"); // NOI18N
        pEquipado.add(arma);

        grupoEquipado.add(anilloIzq);
        anilloIzq.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        anilloIzq.setBorderPainted(false);
        anilloIzq.setEnabled(false);
        anilloIzq.setFocusable(false);
        pEquipado.add(anilloIzq);

        grupoEquipado.add(botas);
        botas.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        botas.setText("Botas");
        botas.setComponentPopupMenu(menuEquipado);
        botas.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botas.setName("botas"); // NOI18N
        pEquipado.add(botas);

        grupoEquipado.add(anilloDer);
        anilloDer.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        anilloDer.setBorderPainted(false);
        anilloDer.setEnabled(false);
        anilloDer.setFocusable(false);
        pEquipado.add(anilloDer);

        separadorInventario.setLeftComponent(pEquipado);

        pInventario.setLayout(new java.awt.GridLayout(4, 5));

        grupoInventario.add(inventario1);
        inventario1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario1.setComponentPopupMenu(menuInventario);
        inventario1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario1.setName("inventario1"); // NOI18N
        pInventario.add(inventario1);

        grupoInventario.add(inventario2);
        inventario2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario2.setComponentPopupMenu(menuInventario);
        inventario2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario2.setName("inventario2"); // NOI18N
        pInventario.add(inventario2);

        grupoInventario.add(inventario3);
        inventario3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario3.setComponentPopupMenu(menuInventario);
        inventario3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario3.setName("inventario3"); // NOI18N
        pInventario.add(inventario3);

        grupoInventario.add(inventario4);
        inventario4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario4.setComponentPopupMenu(menuInventario);
        inventario4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario4.setName("inventario4"); // NOI18N
        pInventario.add(inventario4);

        grupoInventario.add(inventario5);
        inventario5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario5.setComponentPopupMenu(menuInventario);
        inventario5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario5.setName("inventario5"); // NOI18N
        pInventario.add(inventario5);

        grupoInventario.add(inventario6);
        inventario6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario6.setComponentPopupMenu(menuInventario);
        inventario6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario6.setName("inventario6"); // NOI18N
        pInventario.add(inventario6);

        grupoInventario.add(inventario7);
        inventario7.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario7.setComponentPopupMenu(menuInventario);
        inventario7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario7.setName("inventario7"); // NOI18N
        pInventario.add(inventario7);

        grupoInventario.add(inventario8);
        inventario8.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario8.setComponentPopupMenu(menuInventario);
        inventario8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario8.setName("inventario8"); // NOI18N
        pInventario.add(inventario8);

        grupoInventario.add(inventario9);
        inventario9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario9.setComponentPopupMenu(menuInventario);
        inventario9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario9.setName("inventario9"); // NOI18N
        pInventario.add(inventario9);

        grupoInventario.add(inventario10);
        inventario10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario10.setComponentPopupMenu(menuInventario);
        inventario10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario10.setName("inventario10"); // NOI18N
        pInventario.add(inventario10);

        grupoInventario.add(inventario11);
        inventario11.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario11.setComponentPopupMenu(menuInventario);
        inventario11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario11.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario11.setName("inventario11"); // NOI18N
        pInventario.add(inventario11);

        grupoInventario.add(inventario12);
        inventario12.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario12.setComponentPopupMenu(menuInventario);
        inventario12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario12.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario12.setName("inventario12"); // NOI18N
        pInventario.add(inventario12);

        grupoInventario.add(inventario13);
        inventario13.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario13.setComponentPopupMenu(menuInventario);
        inventario13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario13.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario13.setName("inventario13"); // NOI18N
        pInventario.add(inventario13);

        grupoInventario.add(inventario14);
        inventario14.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario14.setComponentPopupMenu(menuInventario);
        inventario14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario14.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario14.setName("inventario14"); // NOI18N
        pInventario.add(inventario14);

        grupoInventario.add(inventario15);
        inventario15.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario15.setComponentPopupMenu(menuInventario);
        inventario15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario15.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario15.setName("inventario15"); // NOI18N
        pInventario.add(inventario15);

        grupoInventario.add(inventario16);
        inventario16.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario16.setComponentPopupMenu(menuInventario);
        inventario16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario16.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario16.setName("inventario16"); // NOI18N
        pInventario.add(inventario16);

        grupoInventario.add(inventario17);
        inventario17.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario17.setComponentPopupMenu(menuInventario);
        inventario17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario17.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario17.setName("inventario17"); // NOI18N
        pInventario.add(inventario17);

        grupoInventario.add(inventario18);
        inventario18.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario18.setComponentPopupMenu(menuInventario);
        inventario18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario18.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario18.setName("inventario18"); // NOI18N
        pInventario.add(inventario18);

        grupoInventario.add(inventario19);
        inventario19.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario19.setComponentPopupMenu(menuInventario);
        inventario19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario19.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario19.setName("inventario19"); // NOI18N
        pInventario.add(inventario19);

        grupoInventario.add(inventario20);
        inventario20.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        inventario20.setComponentPopupMenu(menuInventario);
        inventario20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        inventario20.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inventario20.setName("inventario20"); // NOI18N
        pInventario.add(inventario20);

        separadorInventario.setRightComponent(pInventario);

        pInferior.add(separadorInventario, java.awt.BorderLayout.CENTER);

        add(pInferior);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton anilloDer;
    private javax.swing.JToggleButton anilloIzq;
    private javax.swing.JToggleButton arma;
    private javax.swing.JLabel ataqueOcasionado;
    private javax.swing.JLabel ataqueRecibido;
    private javax.swing.JLabel atributosSinUsar;
    private javax.swing.JToggleButton botas;
    private javax.swing.JButton btnArmadura;
    private javax.swing.JButton btnConstitucion;
    private javax.swing.JButton btnDestreza;
    private javax.swing.JButton btnFuerza;
    private javax.swing.JToggleButton casco;
    private javax.swing.JToggleButton cinta;
    private javax.swing.JToggleButton collar;
    private javax.swing.JLabel combatesTotal;
    private javax.swing.JToggleButton coraza;
    private javax.swing.JLabel derrotasTotal;
    private javax.swing.JMenuItem desequipar;
    private javax.swing.JLabel empatesTotal;
    private javax.swing.JMenuItem equipar;
    private javax.swing.JToggleButton escudo;
    private javax.swing.JLabel etAtaqueOcasionado;
    private javax.swing.JLabel etAtaqueRecibido;
    private javax.swing.JLabel etAtrSinUsar;
    private javax.swing.JLabel etCombates;
    private javax.swing.JLabel etDerrotas;
    private javax.swing.JLabel etEmpates;
    private javax.swing.JLabel etMisiones;
    private javax.swing.JLabel etOroAcumulado;
    private javax.swing.JLabel etTituloAtr;
    private javax.swing.JLabel etTituloEquipado;
    private javax.swing.JLabel etTituloEstadisticas;
    private javax.swing.JLabel etTituloInventario;
    private javax.swing.JLabel etVictorias;
    private javax.swing.ButtonGroup grupoEquipado;
    private javax.swing.ButtonGroup grupoInventario;
    private javax.swing.JToggleButton inventario1;
    private javax.swing.JToggleButton inventario10;
    private javax.swing.JToggleButton inventario11;
    private javax.swing.JToggleButton inventario12;
    private javax.swing.JToggleButton inventario13;
    private javax.swing.JToggleButton inventario14;
    private javax.swing.JToggleButton inventario15;
    private javax.swing.JToggleButton inventario16;
    private javax.swing.JToggleButton inventario17;
    private javax.swing.JToggleButton inventario18;
    private javax.swing.JToggleButton inventario19;
    private javax.swing.JToggleButton inventario2;
    private javax.swing.JToggleButton inventario20;
    private javax.swing.JToggleButton inventario3;
    private javax.swing.JToggleButton inventario4;
    private javax.swing.JToggleButton inventario5;
    private javax.swing.JToggleButton inventario6;
    private javax.swing.JToggleButton inventario7;
    private javax.swing.JToggleButton inventario8;
    private javax.swing.JToggleButton inventario9;
    private javax.swing.JPopupMenu menuEquipado;
    private javax.swing.JPopupMenu menuInventario;
    private javax.swing.JLabel misionesTotal;
    private javax.swing.JLabel oroTotal;
    private javax.swing.JPanel pEquipado;
    private javax.swing.JPanel pEstadisticas;
    private javax.swing.JPanel pInferior;
    private javax.swing.JPanel pInventario;
    private javax.swing.JPanel pSuperior;
    private javax.swing.JPanel pTituloAtr;
    private javax.swing.JPanel pTituloEstadisticas;
    private javax.swing.JPanel panelArmadura;
    private javax.swing.JPanel panelAtrSinUsar;
    private javax.swing.JPanel panelConstitucion;
    private javax.swing.JPanel panelDestreza;
    private javax.swing.JPanel panelFuerza;
    private javax.swing.JToggleButton pantalon;
    private javax.swing.JProgressBar pbArmadura;
    private javax.swing.JProgressBar pbConstitucion;
    private javax.swing.JProgressBar pbDestreza;
    private javax.swing.JProgressBar pbFuerza;
    private javax.swing.JToggleButton pendienteDer;
    private javax.swing.JToggleButton pendienteIzq;
    private javax.swing.JMenuItem potenciar;
    private javax.swing.JMenuItem potenciarE;
    private javax.swing.JPanel psDerecha;
    private javax.swing.JPanel psIzquierda;
    private javax.swing.JSplitPane sTituloInventario;
    private javax.swing.JSplitPane separadorInventario;
    private javax.swing.JMenuItem vender;
    private javax.swing.JLabel victoriasTotal;
    // End of variables declaration//GEN-END:variables

    public void addControlador(ActionListener al) {
        btnFuerza.addActionListener(al);
        btnFuerza.setActionCommand("subirFuerza");
        btnArmadura.addActionListener(al);
        btnArmadura.setActionCommand("subirArmadura");
        btnDestreza.addActionListener(al);
        btnDestreza.setActionCommand("subirDestreza");
        btnConstitucion.addActionListener(al);
        btnConstitucion.setActionCommand("subirConstitucion");
        equipar.addActionListener(al);
        equipar.setActionCommand("equipar");
        desequipar.addActionListener(al);
        desequipar.setActionCommand("desequipar");
        potenciar.addActionListener(al);
        potenciar.setActionCommand("potenciar");
        potenciarE.addActionListener(al);
        potenciarE.setActionCommand("potenciar");
        vender.addActionListener(al);
        vender.setActionCommand("vender");
    }

    public JToggleButton getSeleccionEquipado() {
        try {
            switch (menuEquipado.getInvoker().getName()) {
                case "casco":
                    return casco;
                case "coraza":
                    return coraza;
                case "pantalon":
                    return pantalon;
                case "botas":
                    return botas;
                case "escudo":
                    return escudo;
                case "arma":
                    return arma;
                default:
                    return null;
            }
        } catch (NullPointerException e) {
            return null;
        }
    }

    public JToggleButton getSeleccionInventario() {
        try {
            switch (menuInventario.getInvoker().getName()) {
                case "inventario1":
                    return inventario1;
                case "inventario2":
                    return inventario2;
                case "inventario3":
                    return inventario3;
                case "inventario4":
                    return inventario4;
                case "inventario5":
                    return inventario5;
                case "inventario6":
                    return inventario6;
                case "inventario7":
                    return inventario7;
                case "inventario8":
                    return inventario8;
                case "inventario9":
                    return inventario9;
                case "inventario10":
                    return inventario10;
                case "inventario11":
                    return inventario11;
                case "inventario12":
                    return inventario12;
                case "inventario13":
                    return inventario13;
                case "inventario14":
                    return inventario14;
                case "inventario15":
                    return inventario15;
                case "inventario16":
                    return inventario16;
                case "inventario17":
                    return inventario17;
                case "inventario18":
                    return inventario18;
                case "inventario19":
                    return inventario19;
                case "inventario20":
                    return inventario20;
                default:
                    return null;
            }
        } catch (NullPointerException e) {
            return null;
        }
    }

    public void setAtaqueOcasionado(String ataqueOcasionado) {
        this.ataqueOcasionado.setText(ataqueOcasionado);
    }

    public void setCombatesTotal(String combatesTotal) {
        this.combatesTotal.setText(combatesTotal);
    }

    public void setAtaqueRecibido(String ataqueRecibido) {
        this.ataqueRecibido.setText(ataqueRecibido);
    }

    public void setDerrotasTotal(String derrotasTotal) {
        this.derrotasTotal.setText(derrotasTotal);
    }

    public void setEmpatesTotal(String empatesTotal) {
        this.empatesTotal.setText(empatesTotal);
    }

    public void setEquipado(int indice, String texto, String toolTip) {
        boolean activo = true;
        if (texto == null) {
            activo = false;
        }

        switch (indice) {
            case 0:
                if (texto == null) {
                    casco.setText("Casco");
                } else {
                    casco.setText(texto);
                }
                casco.setEnabled(activo);
                casco.setSelected(false);
                casco.setToolTipText(toolTip);
                break;
            case 1:
                if (texto == null) {
                    coraza.setText("Coraza");
                } else {
                    coraza.setText(texto);
                }
                coraza.setEnabled(activo);
                coraza.setSelected(false);
                coraza.setToolTipText(toolTip);
                break;
            case 2:
                if (texto == null) {
                    pantalon.setText("Pantalon");
                } else {
                    pantalon.setText(texto);
                }
                pantalon.setEnabled(activo);
                pantalon.setSelected(false);
                pantalon.setToolTipText(toolTip);
                break;
            case 3:
                if (texto == null) {
                    botas.setText("Botas");
                } else {
                    botas.setText(texto);
                }
                botas.setEnabled(activo);
                botas.setSelected(false);
                botas.setToolTipText(toolTip);
                break;
            case 4:
                if (texto == null) {
                    escudo.setText("Escudo");
                } else {
                    escudo.setText(texto);
                }
                escudo.setEnabled(activo);
                escudo.setSelected(false);
                escudo.setToolTipText(toolTip);
                break;
            case 5:
                if (texto == null) {
                    arma.setText("Arma");
                } else {
                    arma.setText(texto);
                }
                arma.setEnabled(activo);
                arma.setSelected(false);
                arma.setToolTipText(toolTip);
                break;
        }
    }

    public void setInventario(int indice, String texto, String toolTip) {
        boolean activo = true;
        if (texto == null) {
            activo = false;
        }
        switch (indice) {
            case 0:
                inventario1.setEnabled(activo);
                inventario1.setSelected(false);
                inventario1.setText(texto);
                inventario1.setToolTipText(toolTip);
                break;
            case 1:
                inventario2.setEnabled(activo);
                inventario2.setSelected(false);
                inventario2.setText(texto);
                inventario2.setToolTipText(toolTip);
                break;
            case 2:
                inventario3.setEnabled(activo);
                inventario3.setSelected(false);
                inventario3.setText(texto);
                inventario3.setToolTipText(toolTip);
                break;
            case 3:
                inventario4.setEnabled(activo);
                inventario4.setSelected(false);
                inventario4.setText(texto);
                inventario4.setToolTipText(toolTip);
                break;
            case 4:
                inventario5.setEnabled(activo);
                inventario5.setSelected(false);
                inventario5.setText(texto);
                inventario5.setToolTipText(toolTip);
                break;
            case 5:
                inventario6.setEnabled(activo);
                inventario6.setSelected(false);
                inventario6.setText(texto);
                inventario6.setToolTipText(toolTip);
                break;
            case 6:
                inventario7.setEnabled(activo);
                inventario7.setSelected(false);
                inventario7.setText(texto);
                inventario7.setToolTipText(toolTip);
                break;
            case 7:
                inventario8.setEnabled(activo);
                inventario8.setSelected(false);
                inventario8.setText(texto);
                inventario8.setToolTipText(toolTip);
                break;
            case 8:
                inventario9.setEnabled(activo);
                inventario9.setSelected(false);
                inventario9.setText(texto);
                inventario9.setToolTipText(toolTip);
                break;
            case 9:
                inventario10.setEnabled(activo);
                inventario10.setSelected(false);
                inventario10.setText(texto);
                inventario10.setToolTipText(toolTip);
                break;
            case 10:
                inventario11.setEnabled(activo);
                inventario11.setSelected(false);
                inventario11.setText(texto);
                inventario11.setToolTipText(toolTip);
                break;
            case 11:
                inventario12.setEnabled(activo);
                inventario12.setSelected(false);
                inventario12.setText(texto);
                inventario12.setToolTipText(toolTip);
                break;
            case 12:
                inventario13.setEnabled(activo);
                inventario13.setSelected(false);
                inventario13.setText(texto);
                inventario13.setToolTipText(toolTip);
                break;
            case 13:
                inventario14.setEnabled(activo);
                inventario14.setSelected(false);
                inventario14.setText(texto);
                inventario14.setToolTipText(toolTip);
                break;
            case 14:
                inventario15.setEnabled(activo);
                inventario15.setSelected(false);
                inventario15.setText(texto);
                inventario15.setToolTipText(toolTip);
                break;
            case 15:
                inventario16.setEnabled(activo);
                inventario16.setSelected(false);
                inventario16.setText(texto);
                inventario16.setToolTipText(toolTip);
                break;
            case 16:
                inventario17.setEnabled(activo);
                inventario17.setSelected(false);
                inventario17.setText(texto);
                inventario17.setToolTipText(toolTip);
                break;
            case 17:
                inventario18.setEnabled(activo);
                inventario18.setSelected(false);
                inventario18.setText(texto);
                inventario18.setToolTipText(toolTip);
                break;
            case 18:
                inventario19.setEnabled(activo);
                inventario19.setSelected(false);
                inventario19.setText(texto);
                inventario19.setToolTipText(toolTip);
                break;
            case 19:
                inventario20.setEnabled(activo);
                inventario20.setSelected(false);
                inventario20.setText(texto);
                inventario20.setToolTipText(toolTip);
                break;
        }
    }

    public void setMisionesTotal(String misionesTotal) {
        this.misionesTotal.setText(misionesTotal);
    }

    public void setOroTotal(String oroTotal) {
        this.oroTotal.setText(oroTotal);
    }

    public void setPbArmadura(int max, int valor) {
        this.pbArmadura.setMaximum(max);
        this.pbArmadura.setValue(valor);
        this.pbArmadura.setString("Armadura " + valor);
    }

    public void setPbConstitucion(int max, int valor) {
        this.pbConstitucion.setMaximum(max);
        this.pbConstitucion.setValue(valor);
        this.pbConstitucion.setString("Constitucion " + valor);
    }

    public void setPbDestreza(int max, int valor) {
        this.pbDestreza.setMaximum(max);
        this.pbDestreza.setValue(valor);
        this.pbDestreza.setString("Destreza " + valor);
    }

    public void setPbFuerza(int max, int valor) {
        this.pbFuerza.setMaximum(max);
        this.pbFuerza.setValue(valor);
        this.pbFuerza.setString("Fuerza " + valor);
    }

    public void setVictoriasTotal(String victoriasTotal) {
        this.victoriasTotal.setText(victoriasTotal);
    }

    public void setAtributosSinUsar(String atributosSinUsar) {
        this.atributosSinUsar.setText(atributosSinUsar);
    }
}
