/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panel;

import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;

/**
 *
 * @author Samuel Reyes
 *
 */
public class PanelBazar extends javax.swing.JPanel {

    /**
     * Creates new form PanelMision
     */
    public PanelBazar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNorte = new javax.swing.JPanel();
        separador = new javax.swing.JSplitPane();
        etTitulo = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        listado = new javax.swing.JList<>();

        setMaximumSize(new java.awt.Dimension(700, 550));
        setMinimumSize(new java.awt.Dimension(700, 550));
        setPreferredSize(new java.awt.Dimension(700, 550));
        setLayout(new java.awt.BorderLayout());

        panelNorte.setLayout(new java.awt.BorderLayout());

        separador.setDividerLocation(500);
        separador.setDividerSize(0);
        separador.setEnabled(false);

        etTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        etTitulo.setText("Articulos en venta");
        separador.setLeftComponent(etTitulo);

        btnAceptar.setText("Aceptar compra");
        separador.setRightComponent(btnAceptar);

        panelNorte.add(separador, java.awt.BorderLayout.CENTER);

        add(panelNorte, java.awt.BorderLayout.NORTH);

        listado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listado.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scroll.setViewportView(listado);

        add(scroll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel etTitulo;
    private javax.swing.JList<String> listado;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JSplitPane separador;
    // End of variables declaration//GEN-END:variables

    public void addControlador(ActionListener al) {
        btnAceptar.addActionListener(al);
        btnAceptar.setActionCommand("aceptarCompra");
    }

    public void setArticulos(String[] lista) {
        DefaultListModel modelo = new DefaultListModel();

        for (String articulo : lista) {
            modelo.addElement(articulo);
        }

        listado.setModel(modelo);
    }

    public int getSeleccionado() {
        return listado.getSelectedIndex();
    }
}
