/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panel;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Samuel Reyes
 *
 */
public class PanelDuelo extends javax.swing.JPanel {

    /**
     * Creates new form PanelDuelo
     */
    public PanelDuelo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDuelista1 = new javax.swing.JPanel();
        pd1Foto = new javax.swing.JPanel();
        separador1 = new javax.swing.JSplitPane();
        etNombre1 = new javax.swing.JLabel();
        etFoto1 = new javax.swing.JLabel();
        pd1Estado = new javax.swing.JPanel();
        btnAtacar1 = new javax.swing.JButton();
        pd1Atributos = new javax.swing.JPanel();
        etNivel1 = new javax.swing.JLabel();
        etFuerza1 = new javax.swing.JLabel();
        etArmadura1 = new javax.swing.JLabel();
        etDestreza1 = new javax.swing.JLabel();
        etConstitucion1 = new javax.swing.JLabel();
        pDuelista2 = new javax.swing.JPanel();
        pd2Foto = new javax.swing.JPanel();
        separador2 = new javax.swing.JSplitPane();
        etNombre2 = new javax.swing.JLabel();
        etFoto2 = new javax.swing.JLabel();
        pd2Estado = new javax.swing.JPanel();
        btnAtacar2 = new javax.swing.JButton();
        pd2Atributos = new javax.swing.JPanel();
        etNivel2 = new javax.swing.JLabel();
        etFuerza2 = new javax.swing.JLabel();
        etArmadura2 = new javax.swing.JLabel();
        etDestreza2 = new javax.swing.JLabel();
        etConstitucion2 = new javax.swing.JLabel();
        pDuelista3 = new javax.swing.JPanel();
        pd3Foto = new javax.swing.JPanel();
        separador3 = new javax.swing.JSplitPane();
        etNombre3 = new javax.swing.JLabel();
        etFoto3 = new javax.swing.JLabel();
        pd3Estado = new javax.swing.JPanel();
        btnAtacar3 = new javax.swing.JButton();
        pd3Atributos = new javax.swing.JPanel();
        etNivel3 = new javax.swing.JLabel();
        etFuerza3 = new javax.swing.JLabel();
        etArmadura3 = new javax.swing.JLabel();
        etDestreza3 = new javax.swing.JLabel();
        etConstitucion3 = new javax.swing.JLabel();
        pDuelista4 = new javax.swing.JPanel();
        pd4Foto = new javax.swing.JPanel();
        separador4 = new javax.swing.JSplitPane();
        etNombre4 = new javax.swing.JLabel();
        etFoto4 = new javax.swing.JLabel();
        pd4Estado = new javax.swing.JPanel();
        btnAtacar4 = new javax.swing.JButton();
        pd4Atributos = new javax.swing.JPanel();
        etNivel4 = new javax.swing.JLabel();
        etFuerza4 = new javax.swing.JLabel();
        etArmadura4 = new javax.swing.JLabel();
        etDestreza4 = new javax.swing.JLabel();
        etConstitucion4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(700, 550));
        setMinimumSize(new java.awt.Dimension(700, 550));
        setPreferredSize(new java.awt.Dimension(700, 550));
        setLayout(new java.awt.GridLayout(2, 2));

        pDuelista1.setMaximumSize(new java.awt.Dimension(350, 275));
        pDuelista1.setMinimumSize(new java.awt.Dimension(350, 275));
        pDuelista1.setPreferredSize(new java.awt.Dimension(350, 275));
        pDuelista1.setLayout(new java.awt.GridLayout(1, 2));

        pd1Foto.setLayout(new java.awt.BorderLayout());

        separador1.setDividerLocation(30);
        separador1.setDividerSize(1);
        separador1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        etNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etNombre1.setEnabled(false);
        separador1.setTopComponent(etNombre1);

        etFoto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etFoto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        etFoto1.setEnabled(false);
        separador1.setBottomComponent(etFoto1);

        pd1Foto.add(separador1, java.awt.BorderLayout.CENTER);

        pDuelista1.add(pd1Foto);

        pd1Estado.setLayout(new java.awt.BorderLayout());

        btnAtacar1.setText("Atacar");
        pd1Estado.add(btnAtacar1, java.awt.BorderLayout.PAGE_END);

        pd1Atributos.setLayout(new java.awt.GridLayout(5, 1));

        etNivel1.setEnabled(false);
        pd1Atributos.add(etNivel1);

        etFuerza1.setEnabled(false);
        pd1Atributos.add(etFuerza1);

        etArmadura1.setEnabled(false);
        pd1Atributos.add(etArmadura1);

        etDestreza1.setEnabled(false);
        pd1Atributos.add(etDestreza1);

        etConstitucion1.setEnabled(false);
        pd1Atributos.add(etConstitucion1);

        pd1Estado.add(pd1Atributos, java.awt.BorderLayout.CENTER);

        pDuelista1.add(pd1Estado);

        add(pDuelista1);

        pDuelista2.setMaximumSize(new java.awt.Dimension(350, 275));
        pDuelista2.setMinimumSize(new java.awt.Dimension(350, 275));
        pDuelista2.setPreferredSize(new java.awt.Dimension(350, 275));
        pDuelista2.setLayout(new java.awt.GridLayout(1, 2));

        pd2Foto.setLayout(new java.awt.BorderLayout());

        separador2.setDividerLocation(30);
        separador2.setDividerSize(1);
        separador2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        etNombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etNombre2.setEnabled(false);
        separador2.setTopComponent(etNombre2);

        etFoto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etFoto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        etFoto2.setEnabled(false);
        separador2.setBottomComponent(etFoto2);

        pd2Foto.add(separador2, java.awt.BorderLayout.CENTER);

        pDuelista2.add(pd2Foto);

        pd2Estado.setLayout(new java.awt.BorderLayout());

        btnAtacar2.setText("Atacar");
        pd2Estado.add(btnAtacar2, java.awt.BorderLayout.PAGE_END);

        pd2Atributos.setLayout(new java.awt.GridLayout(5, 1));

        etNivel2.setEnabled(false);
        pd2Atributos.add(etNivel2);

        etFuerza2.setEnabled(false);
        pd2Atributos.add(etFuerza2);

        etArmadura2.setEnabled(false);
        pd2Atributos.add(etArmadura2);

        etDestreza2.setEnabled(false);
        pd2Atributos.add(etDestreza2);

        etConstitucion2.setEnabled(false);
        pd2Atributos.add(etConstitucion2);

        pd2Estado.add(pd2Atributos, java.awt.BorderLayout.CENTER);

        pDuelista2.add(pd2Estado);

        add(pDuelista2);

        pDuelista3.setMaximumSize(new java.awt.Dimension(350, 275));
        pDuelista3.setMinimumSize(new java.awt.Dimension(350, 275));
        pDuelista3.setPreferredSize(new java.awt.Dimension(350, 275));
        pDuelista3.setLayout(new java.awt.GridLayout(1, 2));

        pd3Foto.setLayout(new java.awt.BorderLayout());

        separador3.setDividerLocation(30);
        separador3.setDividerSize(1);
        separador3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        etNombre3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etNombre3.setEnabled(false);
        separador3.setTopComponent(etNombre3);

        etFoto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etFoto3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        etFoto3.setEnabled(false);
        separador3.setBottomComponent(etFoto3);

        pd3Foto.add(separador3, java.awt.BorderLayout.CENTER);

        pDuelista3.add(pd3Foto);

        pd3Estado.setLayout(new java.awt.BorderLayout());

        btnAtacar3.setText("Atacar");
        pd3Estado.add(btnAtacar3, java.awt.BorderLayout.PAGE_END);

        pd3Atributos.setLayout(new java.awt.GridLayout(5, 1));

        etNivel3.setEnabled(false);
        pd3Atributos.add(etNivel3);

        etFuerza3.setEnabled(false);
        pd3Atributos.add(etFuerza3);

        etArmadura3.setEnabled(false);
        pd3Atributos.add(etArmadura3);

        etDestreza3.setEnabled(false);
        pd3Atributos.add(etDestreza3);

        etConstitucion3.setEnabled(false);
        pd3Atributos.add(etConstitucion3);

        pd3Estado.add(pd3Atributos, java.awt.BorderLayout.CENTER);

        pDuelista3.add(pd3Estado);

        add(pDuelista3);

        pDuelista4.setMaximumSize(new java.awt.Dimension(350, 275));
        pDuelista4.setMinimumSize(new java.awt.Dimension(350, 275));
        pDuelista4.setPreferredSize(new java.awt.Dimension(350, 275));
        pDuelista4.setLayout(new java.awt.GridLayout(1, 2));

        pd4Foto.setLayout(new java.awt.BorderLayout());

        separador4.setDividerLocation(30);
        separador4.setDividerSize(1);
        separador4.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        etNombre4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etNombre4.setEnabled(false);
        separador4.setTopComponent(etNombre4);

        etFoto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etFoto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        etFoto4.setEnabled(false);
        separador4.setBottomComponent(etFoto4);

        pd4Foto.add(separador4, java.awt.BorderLayout.CENTER);

        pDuelista4.add(pd4Foto);

        pd4Estado.setLayout(new java.awt.BorderLayout());

        btnAtacar4.setText("Atacar");
        pd4Estado.add(btnAtacar4, java.awt.BorderLayout.PAGE_END);

        pd4Atributos.setLayout(new java.awt.GridLayout(5, 1));

        etNivel4.setEnabled(false);
        pd4Atributos.add(etNivel4);

        etFuerza4.setEnabled(false);
        pd4Atributos.add(etFuerza4);

        etArmadura4.setEnabled(false);
        pd4Atributos.add(etArmadura4);

        etDestreza4.setEnabled(false);
        pd4Atributos.add(etDestreza4);

        etConstitucion4.setEnabled(false);
        pd4Atributos.add(etConstitucion4);

        pd4Estado.add(pd4Atributos, java.awt.BorderLayout.CENTER);

        pDuelista4.add(pd4Estado);

        add(pDuelista4);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtacar1;
    private javax.swing.JButton btnAtacar2;
    private javax.swing.JButton btnAtacar3;
    private javax.swing.JButton btnAtacar4;
    private javax.swing.JLabel etArmadura1;
    private javax.swing.JLabel etArmadura2;
    private javax.swing.JLabel etArmadura3;
    private javax.swing.JLabel etArmadura4;
    private javax.swing.JLabel etConstitucion1;
    private javax.swing.JLabel etConstitucion2;
    private javax.swing.JLabel etConstitucion3;
    private javax.swing.JLabel etConstitucion4;
    private javax.swing.JLabel etDestreza1;
    private javax.swing.JLabel etDestreza2;
    private javax.swing.JLabel etDestreza3;
    private javax.swing.JLabel etDestreza4;
    private javax.swing.JLabel etFoto1;
    private javax.swing.JLabel etFoto2;
    private javax.swing.JLabel etFoto3;
    private javax.swing.JLabel etFoto4;
    private javax.swing.JLabel etFuerza1;
    private javax.swing.JLabel etFuerza2;
    private javax.swing.JLabel etFuerza3;
    private javax.swing.JLabel etFuerza4;
    private javax.swing.JLabel etNivel1;
    private javax.swing.JLabel etNivel2;
    private javax.swing.JLabel etNivel3;
    private javax.swing.JLabel etNivel4;
    private javax.swing.JLabel etNombre1;
    private javax.swing.JLabel etNombre2;
    private javax.swing.JLabel etNombre3;
    private javax.swing.JLabel etNombre4;
    private javax.swing.JPanel pDuelista1;
    private javax.swing.JPanel pDuelista2;
    private javax.swing.JPanel pDuelista3;
    private javax.swing.JPanel pDuelista4;
    private javax.swing.JPanel pd1Atributos;
    private javax.swing.JPanel pd1Estado;
    private javax.swing.JPanel pd1Foto;
    private javax.swing.JPanel pd2Atributos;
    private javax.swing.JPanel pd2Estado;
    private javax.swing.JPanel pd2Foto;
    private javax.swing.JPanel pd3Atributos;
    private javax.swing.JPanel pd3Estado;
    private javax.swing.JPanel pd3Foto;
    private javax.swing.JPanel pd4Atributos;
    private javax.swing.JPanel pd4Estado;
    private javax.swing.JPanel pd4Foto;
    private javax.swing.JSplitPane separador1;
    private javax.swing.JSplitPane separador2;
    private javax.swing.JSplitPane separador3;
    private javax.swing.JSplitPane separador4;
    // End of variables declaration//GEN-END:variables

    public void addControlador(ActionListener al) {
        btnAtacar1.addActionListener(al);
        btnAtacar1.setActionCommand("atacar1");
        btnAtacar2.addActionListener(al);
        btnAtacar2.setActionCommand("atacar2");
        btnAtacar3.addActionListener(al);
        btnAtacar3.setActionCommand("atacar3");
        btnAtacar4.addActionListener(al);
        btnAtacar4.setActionCommand("atacar4");
    }

    public void setDuelista1(String nombre, String foto, String nivel, String fuerza, String armadura, String destreza, String constitucion) {
        if (nombre != null) {
            etNombre1.setText("Lord " + nombre);
            if (foto != null) {
                etFoto1.setIcon(new ImageIcon(foto));
            } else {
                etFoto1.setText("Imagen no disponible");
            }
            etNivel1.setText("Nivel: " + nivel);
            etFuerza1.setText("Fuerza " + fuerza);
            etArmadura1.setText("Armadura: " + armadura);
            etDestreza1.setText("Destreza: " + destreza);
            etConstitucion1.setText("Constitucion: " + constitucion);
            btnAtacar1.setEnabled(true);
        } else {
            btnAtacar1.setEnabled(false);
        }
    }

    public void setDuelista2(String nombre, String foto, String nivel, String fuerza, String armadura, String destreza, String constitucion) {
        if (nombre != null) {
            etNombre2.setText("Lord " + nombre);
            if (foto != null) {
                etFoto2.setIcon(new ImageIcon(foto));
            } else {
                etFoto2.setText("Imagen no disponible");
            }
            etNivel2.setText("Nivel: " + nivel);
            etFuerza2.setText("Fuerza " + fuerza);
            etArmadura2.setText("Armadura: " + armadura);
            etDestreza2.setText("Destreza: " + destreza);
            etConstitucion2.setText("Constitucion: " + constitucion);
            btnAtacar2.setEnabled(true);
        } else {
            btnAtacar2.setEnabled(false);
        }
    }

    public void setDuelista3(String nombre, String foto, String nivel, String fuerza, String armadura, String destreza, String constitucion) {
        if (nombre != null) {
            etNombre3.setText("Lord " + nombre);
            if (foto != null) {
                etFoto3.setIcon(new ImageIcon(foto));
            } else {
                etFoto3.setText("Imagen no disponible");
            }
            etNivel3.setText("Nivel: " + nivel);
            etFuerza3.setText("Fuerza " + fuerza);
            etArmadura3.setText("Armadura: " + armadura);
            etDestreza3.setText("Destreza: " + destreza);
            etConstitucion3.setText("Constitucion: " + constitucion);
            btnAtacar3.setEnabled(true);
        } else {
            btnAtacar3.setEnabled(false);
        }
    }

    public void setDuelista4(String nombre, String foto, String nivel, String fuerza, String armadura, String destreza, String constitucion) {
        if (nombre != null) {
            etNombre4.setText("Lord " + nombre);
            if (foto != null) {
                etFoto4.setIcon(new ImageIcon(foto));
            } else {
                etFoto4.setText("Imagen no disponible");
            }
            etNivel4.setText("Nivel: " + nivel);
            etFuerza4.setText("Fuerza " + fuerza);
            etArmadura4.setText("Armadura: " + armadura);
            etDestreza4.setText("Destreza: " + destreza);
            etConstitucion4.setText("Constitucion: " + constitucion);
            btnAtacar4.setEnabled(true);
        } else {
            btnAtacar4.setEnabled(false);
        }
    }
}
